server:
  host: "0.0.0.0"
  port: 8081

logging:
  level: "info"
  format: "json"

networks:
  networkInfos:
    - name: "base-sepolia"
      rpcURL: "https://sepolia.base.org"
      chainId: 84532
      X402Version: 1
      scheme: "exact"
      
    - name: "base-mainnet"
      rpcURL: "https://mainnet.base.org"
      chainId: 8453
      X402Version: 1
      scheme: "exact"

